name: Deploy to Server

on:
  push:
    branches:
      - main  # Alterar para a branch que você quer que acione o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh ubuntu@152.70.133.123 << 'EOF'
          cd ~/my_flask_app
          git pull origin main
          source ~/myenv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
        EOF
